/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posterinator;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.Integer.parseInt;
import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.imageio.ImageWriteParam;
import javax.imageio.ImageWriter;
import javax.imageio.plugins.jpeg.JPEGImageReadParam;
import javax.imageio.stream.FileImageOutputStream;
import javax.imageio.stream.ImageInputStream;
import javax.swing.JFileChooser;

/**
 *
 * @author Arthur
 */
public class window extends javax.swing.JFrame {
    BufferedImage bi=null;
    BufferedImage biDoppelt=new BufferedImage(6000,6000,BufferedImage.TYPE_INT_RGB); //nicht höher als 5000 setzen sonst OutOfMemoryError!
    String library="";  
    /**
     * Creates new form window
     */
    public window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                super.paintComponent(g);
                zeichnen(g);
            }

        };
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        jTextField1.setText("C:\\Users\\Arthur\\Documents\\Arthur\\Bilder\\Hintergrund\\abstract_bunt.jpg");
        jTextField1.setToolTipText("");

        jTextField2.setText("C:\\Users\\Arthur\\Documents\\Arthur\\Bilder\\Hintergrund");
        jTextField2.setToolTipText("");

        jTextField3.setText("10");

        jTextField4.setText("10");

        jLabel1.setText("Raster wählen:");

        jLabel2.setText("X");

        jLabel3.setText("Y");

        jLabel4.setText("jLabel4");

        jButton2.setText("Bild wählen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Bildbibliothek wählen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Bild speichern unter...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Poster erstellen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Bildbibliothek speichern");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setText("Bildbibliothek lesen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setText("Bildbibliothek laden");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton1)
                    .addComponent(jButton7))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showOpenDialog(this);
        File f=fc.getSelectedFile();        
        jTextField1.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY );
        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showOpenDialog(this);        
        File f=fc.getSelectedFile();        
        jTextField2.setText(f.getAbsolutePath());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Render();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showOpenDialog(this);  
        File f=fc.getSelectedFile();
        System.out.println("Speichern als "+f.getAbsolutePath());
        try {
            ImageIO.write(bi, "jpg", f);
        } catch (IOException ex) {
            System.out.println("Problem beim Speichern aufgetreten!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showOpenDialog(this);   
        File f=fc.getSelectedFile();    
            
        try{         
            PrintWriter pWriter=new PrintWriter(new BufferedWriter(new FileWriter(f.getAbsolutePath()+".txt"))); 
            pWriter.println(library); 
            if (pWriter != null){ 
                pWriter.flush(); 
                pWriter.close(); 
            }
        } catch (IOException e) {
            System.out.println("Problem beim Speichern aufgetreten!");            
        } 
           
         
        System.out.println("Bildbibliothek gespeichert als "+f.getAbsolutePath());
           
        jLabel4.setText("Erfolgreich gespeichert!");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String pfadB=jTextField2.getText();  
        File bilder=new File(pfadB);   // Lesen der Bildbibiliothek      
        File[] Bild=bilder.listFiles();
        if(bilder!=null){
            Bild=bilder.listFiles();  
        }else{
            System.out.println("                    FEHLER !!!");;
        }
            System.out.println("Bildordner gelesen");
            System.out.println("Dateien: "+Bild);        
        
        int anzahlbilder=Bild.length;
        int[][] dB=new int[anzahlbilder][3]; 
        library=pfadB;
             System.out.println("Durchschnittsfarbe der Bilder berechnen");
             System.out.println("Anzahl Bilder: "+anzahlbilder);
        for(anzahlbilder=0; anzahlbilder<Bild.length;anzahlbilder++){
            if (Bild[anzahlbilder]!=null){
                try {
                    BufferedImage biB=ImageIO.read(Bild[anzahlbilder]);  
                    dB[anzahlbilder]=AverageColor(biB,0,0,biB.getWidth(),biB.getHeight());  //Durchschnittsfarbe Bildbibliothekbilder         
                    biB=null;   
                    library+="#"+dB[anzahlbilder][0]+","+dB[anzahlbilder][1]+","+dB[anzahlbilder][2];
                    System.out.println("Bild gelesen : "+(anzahlbilder+1)+" von "+Bild.length);
                } catch (IOException ex) {
                    System.out.println("Fehler aufgetreten beim Lesen der Datei: "+(anzahlbilder+1));
                }
            }                     
            
        }   
        jLabel4.setText("Erfolgreich gelesen!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("/"));
        int zahl = fc.showOpenDialog(this);
        File f=fc.getSelectedFile();
       
        try{
            BufferedReader br=new BufferedReader(new FileReader(f.getAbsolutePath()));
            library=br.readLine();            
            System.out.println("Datei "+f.getAbsolutePath()+" wurde erfolgreich eingelesen!");
        } catch(Exception e){
            System.out.println("Datei nicht gefunden!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * Hauptprozess
     */
    private void Render(){ 
       
                                //Einlesen der Eingaben und Deklarierungen
        String pfadP=jTextField1.getText();
        
    
        
            System.out.println("Bilder werden geladen...");
      
        int rasterX=1;
        int rasterY=1;          
                                                      
         String X=jTextField3.getText();
         try{
            rasterX=Integer.parseInt(X);
            System.out.println("Erfolgreich Textfeld 3 ausgelesen! rasterX="+rasterX);
         }catch(NumberFormatException e){
            System.out.println("Fehler in Textfeld 3 (keine Zahl)");
         }
        
           
            
         String Y=jTextField4.getText();  
         try{
             rasterY=Integer.parseInt(Y);
             System.out.println("Erfolgreich Textfeld 4 ausgelesen! rasterY="+rasterY);
         }catch(NumberFormatException e){
             System.out.println("Fehler in Textfeld 4 (keine Zahl)");
         }
       
        int[][] durchschnittsfarbeP=new int[rasterX*rasterY][3];        
        
            System.out.println("Deklarierung");
        //  Hier beginnt das Lesen der Dateien
        if (pfadP!=null){                                                    //Lesen des Einzelbildes (Poster)
            try {
                bi=ImageIO.read(new File(pfadP));      
                System.out.println("Poster gelesen");
            } catch (IOException ex) {
                System.out.println("Fehler aufgetreten beim Lesen der Datei");
            }
        }
             
             System.out.println("Durchschnittsfarbe der Rasterkästchen berechnen");
        
        int rasterBreite=bi.getWidth()/rasterX;
        int rasterHoehe=bi.getHeight()/rasterY;
             
        for(int x=0;x<rasterX;x++){                   //Das Poster wird in ein Raster unterteilt, dessen Durchschnittsfarben im durchschnittsfarbeP-Array gespeichert werden
            for(int y=0;y<rasterY;y++){         
                durchschnittsfarbeP[x*rasterY+y]=AverageColor(bi,x*rasterBreite,y*rasterHoehe,rasterBreite,rasterHoehe); //durchschnittsfarbe posterraster
                System.out.println("  Durchschnittsfarbe Kästchen Nr. "+(x*rasterY+y)+" Koordinaten: "+x+","+y+":   "+durchschnittsfarbeP[x*rasterY+y]);
            }
             System.out.println("Lesen von Reihe "+x+" erfolgreich");
        }
        
       
        String[] zeile=library.split("#");
        int[][] durchschnittsfarbeB=new int[zeile.length-1][3];
        for(int i=1;i<zeile.length;i++){                
            String[] a=zeile[i].split(",");
            durchschnittsfarbeB[i-1][0]=Integer.parseInt(a[0]);
            durchschnittsfarbeB[i-1][1]=Integer.parseInt(a[1]);
            durchschnittsfarbeB[i-1][2]=Integer.parseInt(a[2]);
                
        }
           
        String[] Bildabfolge=new String[durchschnittsfarbeP.length];
        int[] Bildnummern=Regression(durchschnittsfarbeP,durchschnittsfarbeB);
        
        
        String[] bildInfo=new String[durchschnittsfarbeB.length];
        for(int i=0;i<durchschnittsfarbeB.length;i++){
            bildInfo[i]=i+"#"+durchschnittsfarbeB[i];
            
        }
        
        int[] xKoordinate=new int[Bildnummern.length];
        int[] yKoordinate=new int[Bildnummern.length];        
        int[][] usedDurchschnittsfarbe=new int[Bildnummern.length][3];
        String[] rasterInfo=new String[Bildnummern.length];
        
        System.out.println("Bildabfolgenfarbe");
        for(int i=0;i<Bildnummern.length;i++){
            yKoordinate[i]=i%rasterY;
            xKoordinate[i]=(i-yKoordinate[i])/rasterY;
           // System.out.println( i+" : Farbe:"+durchschnittsfarbeB[Bildnummern[i]]+"  von Bild mit Nr "+(Bildnummern[i]+1)+" passt am besten zum Raster "+i+" mit Farbe: "+durchschnittsfarbeP[i]);
           // System.out.println(xKoordinate[i]+","+yKoordinate[i]);
            usedDurchschnittsfarbe[i]=durchschnittsfarbeB[Bildnummern[i]]; //speichert die zu benutzenden Durchschnittsfarben in einem Array
            rasterInfo[i]=usedDurchschnittsfarbe[i]+"#"+xKoordinate[i]+"#"+yKoordinate[i]+"+";
            
        }
        
        for(int i=0;i<Bildnummern.length;i++){
            for(int p=0;p<Bildnummern.length;p++){
                if(usedDurchschnittsfarbe[i]==usedDurchschnittsfarbe[p] && p!=i && usedDurchschnittsfarbe[i][0]!=1000){
                    rasterInfo[i]+=p+"#";                    
                    usedDurchschnittsfarbe[p][0]=1000;
                    usedDurchschnittsfarbe[p][1]=1000;
                    usedDurchschnittsfarbe[p][2]=1000;
                    
                }
            }
            System.out.println(i+"         "+rasterInfo[i]);
        }
        for(int i=0;i<usedDurchschnittsfarbe.length;i++){        
            System.out.println(usedDurchschnittsfarbe[i][0]+","+usedDurchschnittsfarbe[i][1]+","+usedDurchschnittsfarbe[i][0]);
            
        }
        //Ab hier wird gezeichnet------------------------------
        
        jLabel4.setText("Zeichnen...");
        
        
        Graphics2D g_bi=bi.createGraphics();       
        Graphics2D g_biDoppelt=biDoppelt.createGraphics();     
        g_bi.setColor(new Color(255,255,255));
        g_bi.fillRect(0,0,bi.getWidth(),bi.getHeight());
        g_biDoppelt.setColor(new Color(255,255,255));
        g_biDoppelt.fillRect(0,0,bi.getWidth(),bi.getHeight());
        
        String[] pfad=library.split("#");
        File bilder=new File(pfad[0]);   // Lesen der geladenen Bildbibiliothek      
        File[] Bild=bilder.listFiles(); 
             System.out.println("Anzahl Bilder geladen: "+Bild.length);        
        if(Bild!=null){
            for(int x=0;x<rasterX;x++){
                for(int y=0;y<rasterY;y++){
                    try{
                        BufferedImage bildPoster=ImageIO.read(Bild[Bildnummern[x*rasterY+y]]);
                        int breiteR=bi.getWidth()/rasterX;
                        int hoeheR=bi.getHeight()/rasterY;
                        int hoeheD=biDoppelt.getHeight()/rasterY;
                        int breiteD=biDoppelt.getWidth()/rasterX;
                        g_biDoppelt.drawImage(bildPoster, x*breiteD,y*breiteD,breiteD,hoeheD,this);
                        g_bi.drawImage(bildPoster, x*breiteR,y*hoeheR,breiteR,hoeheR,this);
               
                    }catch(IOException ex){
                        System.out.println("Fehler aufgetreten beim Lesen der Datei: "+(x*rasterY+y+1));
                    }             
                
                    System.out.println((x*rasterY+y+1)+" /"+(rasterX*rasterY)+"  ("+(int)((x*rasterY+y+1)*1.0/((rasterX*rasterY)*1.0)*100)+"%)");
              
                }
            }
        }
        
        System.out.println("Erfolgreich!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11");       
       
        
    }
    
    /**
     * Zeichnen der Objekte in jPanel1
     * @param g Graphics-Objekt
     */
    private void zeichnen(Graphics g){
        
        if(bi!=null){                              // wenn ein Bild geladen ist
            int w=jPanel1.getWidth();
            int hoeheneu=bi.getHeight()*w/bi.getWidth();
            if(hoeheneu>jPanel1.getHeight()){
                hoeheneu=jPanel1.getHeight();
            }
            g.drawImage(bi,0,0,w,hoeheneu,this);
        }else{                                     //wenn noch kein Bild geladen ist
            g.setColor(new Color((int)(Math.random()*256),(int)(Math.random()*256),(int)(Math.random()*256)));
            g.fillRect(0,0,jPanel1.getWidth(),jPanel1.getHeight());
        }
        
    }   
    
    /**
     * Berechnung der Durchschnittsfarbe eines Ausschnitts eines Bildes
     * @param bi das zu verwendete Bild
     * @param X links oben x-Koordinate des Ausschnitts
     * @param Y links oben y-Koordinate des Ausschnitts
     * @param breite Breite des Ausschnitts
     * @param hoehe Höhe des Ausschnitts
     * @return die Durchschnittsfarbe als int array
     */    
    private int[] AverageColor(BufferedImage bi,int X,int Y,int breite, int hoehe){   
        int pixelanzahl=0;  
        int[] C=new int[3];
        System.out.println("    Deklarierung");
        System.out.println("    Berechne...");
            for(pixelanzahl=0;pixelanzahl<Math.sqrt(breite*hoehe);pixelanzahl++){
                int co=bi.getRGB((int)((Math.random()*breite+X)),(int)((Math.random()*hoehe+Y)));
                Color c=new Color(co);
                C[0]+=c.getRed();                                   // Farbwerte werden alle  addiert und ...
                C[1]+=c.getGreen();
                C[2]+=c.getBlue();         
            }
       
        C[0]/=pixelanzahl;                                           // ... durch die Anzahl der ausgwewählten Pixel dividiert
        C[1]/=pixelanzahl;
        C[2]/=pixelanzahl;
       
        
        
        System.out.println("    Erfolgreich! Farbe: "+C[0]+","+C[1]+","+C[2]);
        return C;       
    }
    
    /**Ordnet Farbvektoren zueinander
     * @param P Durchschnittsfarben aller Posterrasterkästchen
     * @param B Durchschnittsfarben aller Bilder aus der Bildbibliothek
     * @return B-Array in der passenden Reihenfolge, das so lang ist, wie die Anzahl der Rasterkästchen
     */
    private int[] Regression(int[][] P, int[][] B){                                //Finde zu jedem Rasterkästchen des Poster das passendste Bild        
        
        int[] bildNr=new int[P.length];              
        int[][] Xbilder=new int[P.length][3];
        for(int j=0;j<P.length;j++){          
            bildNr[j]=kleinsterAbstand(P[j],B);
            System.out.println("        bildNr["+j+"]: "+bildNr[j]);
        }
        
       
        return bildNr;
    }
    
    /**nächster Vektor einer Gruppe zu einem anderen Vektor
     * 
     * @param a entspricht der Durchschnittsfarbe eines Rasterkästchens des Posters   
     * @param b entspricht allen Durchschnittsfarben der Bilder aus der Bildbibliothek
     * @return Nummer des nächstgelegenen Vektors zu a
     */ 
    private int kleinsterAbstand(int[]a, int[][]b){ //berechnet den kleinsten Abstand einer Vektorengruppe und einem Bezugsvektor
        
        int nr=0;
        for(int i=0;i<b.length-1;i++){
            if(Abstand(a,b[i+1])<Abstand(a,b[nr])){
                nr=i+1;               
            }
        }
        System.out.println("                Abstand "+Abstand(a,b[nr]));
        return nr;                                  //gibt die Nummer des Vektors,der am nächsten zum Bezugsvektor a liegt, an
        
    }
    
    /**Abstandsberechnung
     * 
     * @param a Vektor a
     * @param b Vektor b
     * @return Abstand von a und b (ohne Wurzel, da der Abstand nicht nötig ist, sondern nur die Hierarchie von vielen Abständen; spart Rechenarbeit)
     */
    private double Abstand(int[] a, int[] b){        
        return (a[0]-b[0])*(a[0]-b[0])+(a[1]-b[1])*(a[1]-b[1])+(a[2]-b[2])*(a[2]-b[2]);     //Abstandsberechnung
    }    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
